[build]
  command = "CI=false npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  SKIP_PYTHON = "true"
  NODE_VERSION = "18"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
