[build]
  command = "bash ./netlify/build.sh"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "false"
  NETLIFY_USE_PYTHON = "false"
  SKIP_PYTHON = "true"
  SKIP_PYTHON_SETUP = "1"
  CI = "false"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
