[build]
  command = "CI=false npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"
  ignore = "pip install -r requirements.txt"

[build.environment]
  SKIP_PYTHON_INSTALL = "true"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
